version: "3.7"
services:
  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - "5432:5432"
  api:
    build: .
    command: "./bin/sh/wait-for-it.sh db:5432 -- npm run server"
    volumes:
      - ./:/app
      - /app/node_modules
    depends_on:
      - db
    ports:
      - "5000:5000"